//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.PUGSMBFJMSPProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "PUGSMBFJMSP_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PUGSMBFJMSPProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PUGSMBFJMSPProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PUGSMBFJMSPProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PUGSMBFJMSPProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PUGSMBFJMSPProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPUGSMBFJMSPProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PUGSMBFJMSPProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string PUGSMBFJMSPProyectoIPSPackageId = "f6e633d7-c19f-4e35-ad59-b706deb224f6";
		
		// Editor factory identifier
		public const string PUGSMBFJMSPProyectoIPSEditorFactoryId = "49f976d1-261c-4397-a8ec-18a6df8ec66b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PUGSMBFJMSPProyectoIPSModelExplorerToolWindowId = "68bd0ec8-2da7-4b67-8240-7f4c2faa6db6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.PUGSMBFJMSPProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PUGSMBFJMSPProyectoIPSCommandSetId = "272f1018-ff4b-423c-b0f7-716ee3a5238b";
	}
}