//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace UPM_IPS.PUGSMBFJMSPProyectoIPS
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(PUGSMBFJMSPProyectoIPSExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(PUGSMBFJMSPProyectoIPSExplorerToolWindow), Constants.PUGSMBFJMSPProyectoIPSEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@PUGSMBFJMSP_GeneralToolboxTab;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", "UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@VentanaBaseToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.VentanaBaseToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"VentanaBase", 
					"@VentanaBaseToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@VentanaSecToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.VentanaSecToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"VentanaSec", 
					"@VentanaSecToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@ElemBotonToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.ElemBotonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ElemBoton", 
					"@ElemBotonToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@MenuItemToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.MenuItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"MenuItem", 
					"@MenuItemToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@ElemMenuToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.ElemMenuToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ElemMenu", 
					"@ElemMenuToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSP_GeneralToolboxTab",
					"@FinToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.FinToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Fin", 
					"@FinToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxGroup("@ConexionesToolboxTab;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", "UPM_IPS.PUGSMBFJMSPProyectoIPS.ConexionesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.ConexionesToolboxTab",
					"@ConectorBotVentToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.ConectorBotVentToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorBotVent", 
					"@ConectorBotVentToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.PUGSMBFJMSPProyectoIPS.ConexionesToolboxTab",
					"@ConectorVentFinToolboxItem;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					"UPM_IPS.PUGSMBFJMSPProyectoIPS.ConectorVentFinToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorVentFin", 
					"@ConectorVentFinToolboxBitmap;UPM_IPS.PUGSMBFJMSPProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideEditorFactory(typeof(PUGSMBFJMSPProyectoIPSEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(PUGSMBFJMSPProyectoIPSEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(PUGSMBFJMSPProyectoIPSEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"PUGSMBFJMSPProyectoIPS", typeof(PUGSMBFJMSPProyectoIPSEditorFactory))]

	internal abstract partial class PUGSMBFJMSPProyectoIPSPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSPProyectoIPSToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new PUGSMBFJMSPProyectoIPSEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSPProyectoIPSToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			PUGSMBFJMSPProyectoIPSCommandSet commandSet = new PUGSMBFJMSPProyectoIPSCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			PUGSMBFJMSPProyectoIPSClipboardCommandSet clipboardCommandSet = new PUGSMBFJMSPProyectoIPSClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(PUGSMBFJMSPProyectoIPSExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(PUGSMBFJMSPProyectoIPSExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM_IPS.PUGSMBFJMSPProyectoIPS
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSPProyectoIPSDirectiveProcessor), global::UPM_IPS.PUGSMBFJMSPProyectoIPS.PUGSMBFJMSPProyectoIPSDirectiveProcessor.PUGSMBFJMSPProyectoIPSDirectiveProcessorName, "A directive processor that provides access to PUGSMBFJMSPProyectoIPS files")]
	[global::System.Runtime.InteropServices.Guid(Constants.PUGSMBFJMSPProyectoIPSPackageId)]
	internal sealed partial class PUGSMBFJMSPProyectoIPSPackage : PUGSMBFJMSPProyectoIPSPackageBase
	{
	}
}